### ISSUE TITLE
I got "ModuleNotFoundError"

### ISSUE THREAD

**Issue by CaBayTungTang** [italomaia/mangarock.py#1]
I don't know why I always got this error. I even tried reinstalling Python 3.7
Log:
File "e:\mangarock.py-master\src\master\mangarock\main.py", line 5, in <module>
    from mri_to_webp import parse_mri_data_to_webp_buffer
ModuleNotFoundError: No module named 'mri_to_webp'

**Comment by italomaia** [comment]
Strange. Did you try with python3.6? Did you try running from the source code?

**Comment by CaBayTungTang** [comment]
Yes, I tried with python 3.6 and running from the source code. It seems python couldn't see the file mri_to_webp.

**Comment by CaBayTungTang** [comment]
Strange. I added a dot before mri_to_webp and it worked. 

from .mri_to_webp import parse_mri_data_to_webp_buffer
