### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gerald-lbn** [italomaia/mangarock.py#3]
HI when i launched the code i got an error that says:
main.py", line 38
    series_info_json:
                    ^
SyntaxError: invalid syntax

Can you fix this please?

**Comment by italomaia** [comment]
Which version of python did you use? Please, try with 3.6 or above.

**Comment by gerald-lbn** [comment]
i am running python 3.7.3

**Comment by italomaia** [comment]
I just tested with python 3.7.3. Are you absolutely sure you're using python3.7.3 with all dependencies?

**Comment by gerald-lbn** [comment]
absolutely sure here is my `pip freeze`
absl-py==0.7.1
aiohttp==3.5.4
aniso8601==7.0.0
asn1crypto==0.24.0
astor==0.8.0
async-timeout==3.0.1
attrs==19.1.0
Automat==0.7.0
autopep8==1.4.4
backcall==0.1.0
beautifulsoup4==4.7.1
bleach==3.1.0
Brotli==1.0.7
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudflare==2.3.0
cloudscraper==1.1.19
colorama==0.4.1
constantly==15.1.0
cryptography==2.7
cssselect==1.0.3
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
discord.py==1.2.2
docopt==0.6.2
docutils==0.14
entrypoints==0.3
epub==0.5.2
flake8==2.6.2
flake8-docstrings==1.3.0
flake8-polyfill==1.0.2
Flask==1.0.3
Flask-RESTful==0.3.7
fpdf==1.7.2
future==0.17.1
gast==0.2.2
google-pasta==0.1.7
grpcio==1.21.1
gspread==3.1.0
h5py==2.9.0
hacking==1.1.0
httplib2==0.12.3
hyperlink==19.0.0
idna==2.8
img2pdf==0.3.3
incremental==17.5.0
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
itsdangerous==1.1.0
jedi==0.13.3
Jinja2==2.10.1
joblib==0.13.2
Js2Py==0.63
jsonlines==1.2.0
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.5.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Kivy==1.11.0
Kivy-Garden==0.1.4
kiwisolver==1.1.0
lxml==4.3.4
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.5.3
mistune==0.8.4
multidict==4.5.2
nbconvert==5.5.0
nbformat==4.4.0
notebook==5.7.8
numpy==1.16.4
oauth2client==4.1.3
pandocfilters==1.4.2
parsel==1.5.1
parso==0.4.0
pbr==5.3.1
pickleshare==0.7.5
Pillow==6.0.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.8.0
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycodestyle==2.0.0
pycparser==2.19
PyDispatcher==2.0.5
pydocstyle==3.0.0
pyflakes==1.2.3
Pygments==2.4.2
PyHamcrest==1.9.0
pyjsparser==2.7.1
pyOpenSSL==19.0.0
pyparsing==2.4.0
PyPDF2==1.26.0
pyrsistent==0.15.2
python-dateutil==2.8.0
python-slugify==2.0.1
pytz==2019.1
pywinpty==0.5.5
PyYAML==5.1
pyzmq==18.0.1
qtconsole==4.5.1
requests==2.22.0
requests-toolbelt==0.9.1
rsa==4.0
scikit-learn==0.21.2
scipy==1.3.0
Send2Trash==1.5.0
six==1.12.0
slugify==0.0.1
snowballstemmer==1.2.1
soupsieve==1.9.1
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.2
tqdm==4.32.1
traitlets==4.3.2
tzlocal==1.5.1
Unidecode==1.0.23
urllib3==1.25.3
virtualenv==16.6.0
w3lib==1.20.0
Wand==0.5.4
wcwidth==0.1.7
webencodings==0.5.1
websockets==6.0
Werkzeug==0.14.1
widgetsnbextension==3.4.2
wrapt==1.11.2
xlrd==1.2.0
yarl==1.3.0
youtube-dl==2019.6.8
zope.interface==4.6.0

**Comment by italomaia** [comment]
I just pushed a dockerfile for it. Would you mind testing?

**Comment by Shinyhero36** [comment]
How do i proceed?

**Comment by gerald-lbn** [comment]
Yeah now it's working, could you add the possibility to directly convert webp to png or jpg image format?

**Comment by italomaia** [comment]
Maybe. Not a feature I'm looking for currently, but pull requests are welcomed.
